[package]
name = "gwvm"
version = "0.1.0"
authors = ["qiaojinxia <1158829384@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5"
walkdir = "2"
clap = "2.32.0"
hex = "0.3"